name: MSBuild - Multi-Arch

on:
  push:
    branches:
      - main  # La action si esegue solo su push al branch main
  pull_request:
    branches:
      - main  # Esegue la build su PR aperte per testare prima del merge

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64, ARM, ARM64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore GTFractals.sln

    - name: Build Solution
      run: msbuild GTFractals.sln /m /p:Configuration=Release /p:Platform=${{ matrix.platform }} /t:GTFractals
